### ISSUE TITLE
What is the 3Dtouch/Probe stop pin?

### ISSUE THREAD

**Issue by adam-huganir** [tronxy3d/F4xx-SIM240x320#1]
I was setting up BLTouch and was trying to find the right pin in the firmware. I tried the pin [referenced here](https://github.com/tronxy3d/F4xx-SIM240x320/blob/firmware/Marlin/src/pins/stm32f4/pins_TRONXY_F446.h#L62) at `PE3` but did not have any luck. For reference this is the pin:

https://github.com/adam-huganir/misc/blob/5caa66559b70c649ae43909f567975f591d1a3d4/20230111_183218.jpg

Thanks

**Comment by tronxy3d** [comment]
BLTouch need two pins, one pwm pin and one signal pin
It's PC13 not PE3 on that port

**Comment by tronxy3d** [comment]
BLTouch need two pins, one out pin and one signal pin
It's PC13 not PE3 on that port

**Comment by adam-huganir** [comment]
thank you!
